# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Paul Richeson
"""The viewer's javascript: one copy, and a decoder that agrees with Rust.

THERE ARE THREE IMPLEMENTATIONS OF THE FRAME FORMAT AND ONLY TWO OF THEM ARE
CHECKED BY THE REST OF THE SUITE. src/entropy.rs writes it, tests/frames_fixture.rs
pins the bytes it writes, and src/frames.js reads those bytes in a browser
where nothing else in this project runs. A change to the encoder that the
fixture accepts and the javascript does not is a change that ships a working
page today and a blank one next month, silently, on somebody else's website.

So this does two things the other suites cannot:

  1. The copy of src/frames.js embedded in ./radbeeper is byte-for-byte the
     file. The Rust gets its copy from include_str! and cannot drift; the
     Python is installed as a lone file and has to carry one, so the copy is
     generated by tools/embedjs.py and verified here.

  2. The javascript decodes the committed fixture to exactly what the Rust
     says is in it, chain links included -- when node is available. It is
     skipped and not failed when it is not, because node is not a build
     dependency of this project and must not become one.
"""
import json
import os
import re
import subprocess
import sys
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JS = os.path.join(ROOT, "src", "frames.js")
FIXTURE = os.path.join(ROOT, "tests", "fixtures", "frames.bin")
EXPECTED = os.path.join(ROOT, "tests", "fixtures", "frames.json")


def node():
    """The node binary, or None -- it is a convenience here, not a dependency."""
    for name in ("node", "nodejs"):
        try:
            subprocess.run([name, "--version"], capture_output=True, timeout=20,
                           check=True)
            return name
        except (OSError, subprocess.SubprocessError):
            continue
    return None


class TestTheEmbeddedCopyIsTheFile(unittest.TestCase):
    def test_radbeeper_carries_the_javascript_verbatim(self):
        with open(JS, encoding="utf-8") as f:
            source = f.read()
        with open(os.path.join(ROOT, "radbeeper"), encoding="utf-8") as f:
            text = f.read()
        m = re.search(r'VIEWER_JS = r"""(.*?)"""\n# --->8---', text, re.S)
        self.assertIsNotNone(
            m, "no embedded javascript block in radbeeper -- run "
               "python3 tools/embedjs.py")
        self.assertEqual(
            m.group(1), source,
            "radbeeper's copy of src/frames.js is stale. It is generated, not "
            "maintained: run `python3 tools/embedjs.py`. Until you do, the "
            "page the Python writes differs from the page the Rust writes and "
            "the differential suite will fail on every export.")

    def test_the_generator_agrees_that_it_is_current(self):
        out = subprocess.run(
            [sys.executable, os.path.join(ROOT, "tools", "embedjs.py"), "--check"],
            capture_output=True, text=True, timeout=60)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)

    def test_the_javascript_has_no_dependencies(self):
        """A require() or an import would be a dependency on a bundler.

        The page is opened off a disk as often as off a server, and a module
        that has to be resolved is a module that is not there when it is.
        """
        with open(JS, encoding="utf-8") as f:
            source = f.read()
        # MODULE SYNTAX AS A STATEMENT, not as a substring. The first version
        # of this searched for `from "` anywhere and caught
        # `field("from ", ...)` -- the date box's label. A test that fails on
        # a UI string is a test people learn to edit rather than believe.
        for pattern in (r"^\s*import\s", r"^\s*export\s", r"\bimport\s*\(",
                        r"^\s*(?:var|let|const)?\s*\w*\s*=?\s*require\s*\("):
            found = [n + 1 for n, line in enumerate(source.split("\n"))
                     if re.search(pattern, line)
                     and "typeof module" not in line]
            # The one require is the test hook at the bottom, guarded by a
            # `typeof module` check on the line above it.
            found = [n for n in found
                     if "module.exports" not in source.split("\n")[n - 3:n][0:1]]
            self.assertEqual(
                [n for n in found if n < len(source.split("\n")) - 12], [],
                "module syntax at line(s) %s -- the viewer has to run from a "
                "<script> tag off a file:// URL with no bundler" % found)
        self.assertNotIn("</script", source,
                         "a literal </script would end the tag it is inside")
        # No network: the page must work with the machine unplugged. The SVG
        # namespace is a name and not an address -- nothing fetches it.
        self.assertNotIn("http://", source.replace("http://www.w3.org/2000/svg", ""))
        self.assertNotIn("https://", source)


class TestTheJavascriptReadsWhatTheRustWrote(unittest.TestCase):
    """The fixture, decoded by the browser's copy of the format."""

    @classmethod
    def setUpClass(cls):
        cls.NODE = node()
        if cls.NODE is None:
            raise unittest.SkipTest("no node to run the viewer against")
        if not os.path.exists(FIXTURE):
            raise unittest.SkipTest("no frame fixture -- "
                                    "RB_WRITE_FIXTURE=1 cargo test --test frames_fixture")

    def run_js(self, body):
        script = ("var m = require(%s);\nvar fs = require('fs');\n"
                  % json.dumps(JS)) + body
        out = subprocess.run([self.NODE, "-e", script], capture_output=True,
                             text=True, timeout=60)
        self.assertEqual(out.returncode, 0, out.stdout + out.stderr)
        return out.stdout.strip()

    def test_every_frame_decodes_to_the_same_thing(self):
        got = json.loads(self.run_js(
            "var buf = new Uint8Array(fs.readFileSync(%s));\n"
            "var f = m.readFrames(buf);\n"
            "console.log(JSON.stringify(f.map(function (x) {\n"
            "  return {seq: x.seq, started: x.started, suspect: x.suspect,\n"
            "          key: x.key, link: x.link, samples: x.samples};\n"
            "})));" % json.dumps(FIXTURE)))
        with open(EXPECTED, encoding="utf-8") as f:
            want = json.load(f)
        self.assertEqual(len(got), len(want),
                         "the javascript found %d frames, the Rust wrote %d"
                         % (len(got), len(want)))
        for g, w in zip(got, want):
            self.assertEqual(g["seq"], w["seq"])
            self.assertEqual(g["started"], w["started"])
            self.assertEqual(g["suspect"], w["suspect"])
            self.assertEqual(g["key"], w["key"])
            self.assertEqual(g["link"], w["link"])
            self.assertEqual([list(s) for s in g["samples"]],
                             [list(s) for s in w["samples"]],
                             "frame %d's seconds differ" % w["seq"])

    def test_the_chain_recomputes_in_javascript(self):
        """The links the Rust wrote are the links the browser derives.

        Two sha256 implementations and two hex conventions have to agree for
        this to pass, which is the point: the chain is only tamper-evidence if
        a reader can recompute it without the writer's code.
        """
        got = self.run_js(
            "var buf = new Uint8Array(fs.readFileSync(%s));\n"
            "var f = m.readFrames(buf);\n"
            "var prev = m.GENESIS, bad = 0;\n"
            "for (var i = 0; i < f.length; i++) {\n"
            "  prev = m.chainStep(prev, f[i].key);\n"
            "  if (prev !== f[i].link) bad++;\n"
            "}\n"
            "console.log(bad + ' of ' + f.length);" % json.dumps(FIXTURE))
        self.assertTrue(got.startswith("0 of "), "links disagree: " + got)
        self.assertNotEqual(got, "0 of 0", "no frames were checked")

    def test_the_chain_is_verified_in_file_order_and_not_by_sequence(self):
        """`seq` is the pool's counter and it restarts. It is not the order.

        A service restart sets it back to zero, and each tube counts its own,
        so a real month reads 0 0 1 0 0 0 0 1 2 99. The exporter builds the
        chain in FILE order; a viewer that sorted by `seq` before checking
        would shuffle the rows out of the order their links were computed in
        and report breaks in a sound chain. The first page rendered against
        real logs claimed three of them.
        """
        rows = self.run_js(
            "var keys = ['a1','b2','c3','d4'].map(function (x) {\n"
            "  return m.sha256(new Uint8Array(Buffer.from(x)));\n"
            "});\n"
            "var prev = m.GENESIS, rows = [];\n"
            "// Sequence numbers that restart, as a real log's do.\n"
            "var seqs = [7, 0, 1, 0];\n"
            "for (var i = 0; i < keys.length; i++) {\n"
            "  prev = m.chainStep(prev, keys[i]);\n"
            "  rows.push({seq: seqs[i], key: keys[i], link: prev});\n"
            "}\n"
            "m.verifyChain(rows);\n"
            "var inFile = rows.filter(function (r) { return r.chain === 'ok'; }).length;\n"
            "var shuffled = rows.slice().sort(function (a, b) { return a.seq - b.seq; });\n"
            "m.verifyChain(shuffled);\n"
            "var bySeq = shuffled.filter(function (r) { return r.chain === 'ok'; }).length;\n"
            "console.log(inFile + ' ' + bySeq);")
        in_file, by_seq = (int(x) for x in rows.split())
        self.assertEqual(in_file, 4, "a sound chain did not verify in file order")
        self.assertLess(by_seq, 4,
                        "sorting by seq did not disturb the chain, so this "
                        "test is no longer testing anything")

    def test_one_bad_timestamp_does_not_flatten_the_range(self):
        """A 1969 row must not make every real bar land in the last pixel.

        Emissions written by a build that used time.monotonic() date
        themselves to 1969. One of them among a month of good rows spans
        fifty-seven years, and the range selector becomes a blank box. They
        are still listed -- they are evidence -- they just get no vote on the
        scale.
        """
        got = self.run_js(
            "var tsv = '#seq\\tstarted\\tsamples\\tcounts\\tcpm\\tusvh\\tbits"
            "\\tflat\\tband\\tlog_cpm\\tkey\\tlink\\n'\n"
            "  + '0\\t1969-12-31T21:01:12\\t10\\t5\\t30\\t0.2\\t250\\tyes"
            "\\tnominal\\t--\\taa\\tbb\\n'\n"
            "  + '1\\t2026-09-04T18:00:00\\t10\\t5\\t30\\t0.2\\t250\\tyes"
            "\\tnominal\\t--\\tcc\\tdd\\n'\n"
            "  + '2\\t2026-09-04T19:00:00\\t10\\t5\\t30\\t0.2\\t250\\tyes"
            "\\tnominal\\t--\\tee\\tff\\n';\n"
            "var rows = m.parseTsv(tsv);\n"
            "console.log(rows.length);")
        self.assertEqual(got, "3", "the bad row was dropped instead of kept")

    def test_sha256_is_sha256(self):
        got = self.run_js(
            "function b(s){return new Uint8Array(Buffer.from(s,'utf8'));}\n"
            "console.log([m.sha256(b('')), m.sha256(b('abc')),\n"
            "             m.sha256(b('a'.repeat(1000)))].join(' '));")
        self.assertEqual(got.split(), [
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            "41edece42d63e8d9bf515a9ba6932e1c20cbc9f5a5d134645adb5db1b9737ea3",
        ])

    def test_a_damaged_frame_costs_one_frame_here_too(self):
        """The scan-forward recovery has to work in the browser as well.

        A reader that gives up at the first bad byte turns a half-written file
        -- which is what a page published while the service was mid-append
        contains -- into a blank viewer.
        """
        got = self.run_js(
            "var buf = new Uint8Array(fs.readFileSync(%s));\n"
            "var whole = m.readFrames(buf).length;\n"
            "var hurt = buf.slice();\n"
            "// corrupt the body of the second frame\n"
            "var at = 0, seen = 0;\n"
            "for (var i = 4; i < hurt.length - 4; i++) {\n"
            "  if (hurt[i] === 0x52 && hurt[i+1] === 0x42 && hurt[i+2] === 0x46) {\n"
            "    seen++; if (seen === 1) { at = i; break; }\n"
            "  }\n"
            "}\n"
            "hurt[at + 8] ^= 0xff; hurt[at + 9] ^= 0xff;\n"
            "console.log(whole + ' ' + m.readFrames(hurt).length);"
            % json.dumps(FIXTURE))
        whole, after = (int(x) for x in got.split())
        self.assertGreaterEqual(whole, 4)
        self.assertGreaterEqual(after, whole - 2,
                                "damage to one frame lost %d of %d"
                                % (whole - after, whole))


if __name__ == "__main__":
    unittest.main()
